version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-75-238-138.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d836ocb2abcksa
            schema: schema.graphql
            user: ejgkqruosldrtr
            password: f67b0b43b7fb6f7bcd652b1c411a7912a35a9bf3c8ce15f854880e56550f039f
            migrations: true